'use strict';
const { Model } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
  class VisitorAccessCode extends Model {
    /**
     * Sequelize automatically calls this to define relationships.
     */
    static associate(models) {
      // Belongs to Door
      VisitorAccessCode.belongsTo(models.Door, {
        foreignKey: 'doorId',
        as: 'door'
      });

      

      // Generated by Employee (User)
      VisitorAccessCode.belongsTo(models.User, {
        foreignKey: 'employeeId',
        as: 'generatedBy'
      });
    }
  }

  VisitorAccessCode.init(
    {
      code:        DataTypes.STRING,   
      validUntil:  DataTypes.DATE,
      startTime:  DataTypes.DATE,
      endTime:    DataTypes.DATE,
      visitorId:  DataTypes.INTEGER,
      doorId:     DataTypes.INTEGER,
      employeeId: DataTypes.INTEGER  
    },
    {
      sequelize,
      modelName: 'VisitorAccessCode',
    }
  );

  return VisitorAccessCode;
};
